<p class="text-muted lead text-center mb-5">In our Ladies department we offer wide selection of the best products we have found and carefully selected worldwide. Pellentesque habitant morbi tristique senectus et netuss.</p>
            <div class="row gy-5 align-items-stretch">
              <div class="col-lg-4 col-md-6">
                <!-- Product-->
                <div class="product h-100">
                  <div class="product-image"><a href="shop-detail.html"><img class="img-fluid" src="img/product1.jpg" alt="Fur coat with very but very very long name"></a></div>
                  <div class="py-4 px-3 text-center">
                    <h3 class="h5 text-uppercase mb-3"><a class="reset-link" href="shop-detail.html">Fur coat with very but very very long name</a></h3>
                    <p class="mb-0">$143.00
                    </p>
                  </div>
                  <ul class="list-unstyled p-0 ribbon-holder mb-0">
                  </ul>
                </div>
              </div>
              <div class="col-lg-4 col-md-6">
                <!-- Product-->
                <div class="product h-100">
                  <div class="product-image"><a href="shop-detail.html"><img class="img-fluid" src="img/product2.jpg" alt="White Blouse Armani"></a></div>
                  <div class="py-4 px-3 text-center">
                    <h3 class="h5 text-uppercase mb-3"><a class="reset-link" href="shop-detail.html">White Blouse Armani</a></h3>
                    <p class="mb-0">
                      <del class="text-gray-500 me-2">$200.00</del>$143.00
                    </p>
                  </div>
                  <ul class="list-unstyled p-0 ribbon-holder mb-0">
                    <li class="mb-1">
                      <div class="ribbon sale ribbon-primary">SALE</div>
                    </li>
                    <li class="mb-1">
                      <div class="ribbon new ribbon-info">NEW</div>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-4 col-md-6">
                <!-- Product-->
                <div class="product h-100">
                  <div class="product-image"><a href="shop-detail.html"><img class="img-fluid" src="img/product3.jpg" alt="Black Blouse Versace"></a></div>
                  <div class="py-4 px-3 text-center">
                    <h3 class="h5 text-uppercase mb-3"><a class="reset-link" href="shop-detail.html">Black Blouse Versace</a></h3>
                    <p class="mb-0">$143.00
                    </p>
                  </div>
                  <ul class="list-unstyled p-0 ribbon-holder mb-0">
                  </ul>
                </div>
              </div>
              <div class="col-lg-4 col-md-6">
                <!-- Product-->
                <div class="product h-100">
                  <div class="product-image"><a href="shop-detail.html"><img class="img-fluid" src="img/product4.jpg" alt="Black Blouse Versace"></a></div>
                  <div class="py-4 px-3 text-center">
                    <h3 class="h5 text-uppercase mb-3"><a class="reset-link" href="shop-detail.html">Black Blouse Versace</a></h3>
                    <p class="mb-0">$143.00
                    </p>
                  </div>
                  <ul class="list-unstyled p-0 ribbon-holder mb-0">
                  </ul>
                </div>
              </div>
              <div class="col-lg-4 col-md-6">
                <!-- Product-->
                <div class="product h-100">
                  <div class="product-image"><a href="shop-detail.html"><img class="img-fluid" src="img/product3.jpg" alt=" White Blouse Armani"></a></div>
                  <div class="py-4 px-3 text-center">
                    <h3 class="h5 text-uppercase mb-3"><a class="reset-link" href="shop-detail.html"> White Blouse Armani</a></h3>
                    <p class="mb-0">
                      <del class="text-gray-500 me-2">$200.00</del>$143.00
                    </p>
                  </div>
                  <ul class="list-unstyled p-0 ribbon-holder mb-0">
                    <li class="mb-1">
                      <div class="ribbon sale ribbon-primary">SALE</div>
                    </li>
                    <li class="mb-1">
                      <div class="ribbon new ribbon-info">NEW</div>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-4 col-md-6">
                <!-- Product-->
                <div class="product h-100">
                  <div class="product-image"><a href="shop-detail.html"><img class="img-fluid" src="img/product4.jpg" alt="White Blouse Versace"></a></div>
                  <div class="py-4 px-3 text-center">
                    <h3 class="h5 text-uppercase mb-3"><a class="reset-link" href="shop-detail.html">White Blouse Versace</a></h3>
                    <p class="mb-0">$143.00
                    </p>
                  </div>
                  <ul class="list-unstyled p-0 ribbon-holder mb-0">
                    <li class="mb-1">
                      <div class="ribbon new ribbon-info">NEW</div>
                    </li>
                  </ul>
                </div>
              </div>
            </div><a class="d-block text-center py-4"><img class="img-fluid" src="img/banner2.jpg" alt="banner"></a>
            <div class="text-center mb-5"><a class="btn btn-outline-primary" href="#"><i class="fas fa-angle-down me-2"></i>Load more</a></div>
            <nav aria-label="Page navigation example">
              <ul class="pagination justify-content-center">
                <li class="page-item"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">4</a></li>
                <li class="page-item"><a class="page-link" href="#">5</a></li>
                <li class="page-item"><a class="page-link" href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>
              </ul>
            </nav>
          </div>