<?= $this->doctype() ?>
<html lang="en">

<head>
  <meta charset="utf-8">
  <?php $appName = $this->layout()->isLive ? 'Husol Store' : 'BETA Husol Store'; ?>
  <?= $this->headTitle("{$appName} {$this->layout()->appVersion}")->setSeparator(' - ')->setAutoEscape(false) ?>

  <?= $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
  ?>

  <!-- Styles -->
  <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'])
    ->prependStylesheet($this->basePath("css/style.{$this->layout()->dateVersion}.css"))
    ->prependStylesheet($this->basePath("css/hus.{$this->layout()->dateVersion}.css"))
    ->prependStylesheet($this->basePath("css/toastr.min.{$this->layout()->dateVersion}.css"))
    ->prependStylesheet($this->basePath("css/jquery-ui-1.12.1.min.{$this->layout()->dateVersion}.css"))
    ->prependStylesheet($this->basePath("css/bootstrap-4.4.1.min.{$this->layout()->dateVersion}.css"))
    ->prependStylesheet($this->basePath("css/fontawesome-5.12.1.min.{$this->layout()->dateVersion}.css"))
    ->prependStylesheet($this->basePath("css/style.default.min.{$this->layout()->dateVersion}.css"))
    ->prependStylesheet($this->basePath("css/choices.min.{$this->layout()->dateVersion}.css"))
    ->prependStylesheet($this->basePath("css/swiper-bundle.min.{$this->layout()->dateVersion}.css"))
    ->prependStylesheet("https://fonts.googleapis.com/css?family=Roboto:300,400,700")
  ?>

  <!-- Scripts -->
  <?= $this->headScript()
    ->prependFile($this->basePath("js/hus.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/autoNumeric.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/jquery-ui-contextmenu.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/jquery.mask-1.7.7.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/toastr.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/ckeditor.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/bootstrap-select.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/jquery.serializejson.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/jquery-ui-1.12.1.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/bootstrap-4.4.1.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/fontawesome-5.12.1.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/popper.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/jquery-3.4.1.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/bootstrap.bundle.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/noframework.waypoints.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/swiper-bundle.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/choices.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/theme.{$this->layout()->dateVersion}.js"))
  ?>
</head>

<body>
  <?= $this->render('js_variables.phtml') ?>
  <!-- The Modal -->
  <div id="commonDialog" class="modal fade" role="dialog" tabindex="-1"></div>
  <div id="childDialog" class="modal fade" role="dialog" tabindex="-1"></div>
  <div class="wide" id="all">
    <!-- Top bar-->
    <div class="top-bar py-2" id="topBar" style="background: #555">
      <div class="container px-lg-0 text-light py-1">
        <div class="row d-flex align-items-center">
          <div class="col-md-6 d-md-block d-none">
            <p class="mb-0 text-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
          </div>
          <div class="col-md-6">
            <div class="d-flex justify-content-md-end justify-content-between">
              <ul class="list-inline d-block d-md-none mb-0">
                <li class="list-inline-item"><a class="text-xs" href="#"><i class="fa fa-phone"></i></a></li>
                <li class="list-inline-item"><a class="text-xs" href="#"><i class="fa fa-envelope"></i></a></li>
              </ul>
              <ul class="list-inline mb-0">
                <li class="list-inline-item"><a class="text-xs text-uppercase fw-bold text-reset" href="#" data-bs-toggle="modal" data-bs-target="#login-modal"><i class="fas fa-door-open me-2"></i><span class="d-none d-md-inline-block">Sign In</span></a></li>
                <li class="list-inline-item"><a class="text-xs text-uppercase fw-bold text-reset" href="customer-register.html"><i class="fas fa-user me-2"></i><span class="d-none d-md-inline-block">Sign Up</span></a></li>
              </ul>
              <ul class="list-inline mb-0 ms-lg-4">
                <li class="list-inline-item text-gray-600 m-0"><a class="text-xs social-link-hover" href="#" title="Facebook"><i class="fab fa-facebook-f"></i></a></li>
                <li class="list-inline-item text-gray-600 m-0"><a class="text-xs social-link-hover" href="#" title="Twitter"><i class="fab fa-twitter"></i></a></li>
                <li class="list-inline-item text-gray-600 m-0"><a class="text-xs social-link-hover" href="#" title="Linkedin"><i class="fab fa-linkedin-in"></i></a></li>
                <li class="list-inline-item text-gray-600 m-0"><a class="text-xs social-link-hover" href="#" title="Email"><i class="fas fa-envelope"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Top bar end-->

<?= $this->render('navbar.phtml') ?>
    <!-- HEADING BREADCRUMB-->
    <section class="bg-pentagon py-4">
      <div class="container py-3">
        <div class="row d-flex align-items-center gy-4">
          <div class="col-md-7">
            <h1 class="h2 mb-0 text-uppercase">Products</h1>
          </div>
          <div class="col-md-5">
            <!-- Breadcrumb-->
            <ol class="text-sm justify-content-start justify-content-lg-end mb-0 breadcrumb undefined">
              <li class="breadcrumb-item"><a class="text-uppercase" href="index.html">Home</a></li>
              <li class="breadcrumb-item text-uppercase active">Products </li>
            </ol>
          </div>
        </div>
      </div>
    </section>
    <!-- SHOP SECTION-->
    <section class="py-5">
      <div class="container py-4">
        <div class="row g-5">
          <?= $this->render('sidebar.phtml') ?>

          <div class="col-lg-9">
            <?= $this->content ?>
          </div>

        </div>
      </div>
    </section>
    <!--Footer-->
    <footer>
      <!-- MAIN FOOTER-->
      <div class="bg-gray-700 text-white py-5">
        <div class="container py-4">
          <div class="row gy-4">
            <div class="col-lg-3">
              <h4 class="mb-3 text-uppercase">About Us</h4>
              <p class="text-sm text-gray-500">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
              <hr>
              <h4 class="h6 text-uppercase">Join Our Monthly Newsletter</h4>
              <form>
                <div class="input-group border mb-3">
                  <input class="form-control bg-none border-0 shadow-0 text-white" type="email" placeholder="Email address" aria-label="Email address" aria-describedby="button-submit">
                  <button class="btn btn-outline-light bg-none border-0" id="button-submit" type="button"><i class="fas fa-paper-plane"></i></button>
                </div>
              </form>
            </div>
            <div class="col-lg-3">
              <h4 class="mb-3 text-uppercase">Blog</h4>
              <ul class="list-unstyled">
                <li class="d-flex align-items-center mb-2"><a href="blog-post.html"><img class="img-fluid" src="img/detailsquare.jpg" alt="..." width="40"></a>
                  <div class="ms-2">
                    <h6 class="text-uppercase mb-0"> <a class="text-reset" href="blog-post.html">Blog post name</a></h6>
                  </div>
                </li>
                <li class="d-flex align-items-center mb-2"><a href="blog-post.html"><img class="img-fluid" src="img/detailsquare.jpg" alt="..." width="40"></a>
                  <div class="ms-2">
                    <h6 class="text-uppercase mb-0"> <a class="text-reset" href="blog-post.html">Blog post name</a></h6>
                  </div>
                </li>
                <li class="d-flex align-items-center mb-2"><a href="blog-post.html"><img class="img-fluid" src="img/detailsquare.jpg" alt="..." width="40"></a>
                  <div class="ms-2">
                    <h6 class="text-uppercase mb-0"> <a class="text-reset" href="blog-post.html">Very very long blog post name</a></h6>
                  </div>
                </li>
              </ul>
            </div>
            <div class="col-lg-3">
              <h4 class="mb-3 text-uppercase">Contact</h4>
              <p class="text-uppercase text-sm text-gray-500"><strong>Universal Ltd.</strong><br>13/25 New Avenue <br>Newtown upon River <br>45Y 73J <br>England <br><strong>Great Britain</strong></p><a class="btn btn-primary" href="contact.html">Go to contact page</a>
            </div>
            <div class="col-lg-3">
              <ul class="list-inline mb-0">
                <li class="list-inline-item mb-2 me-2 pb-1"><a href="#"><img class="img-fluid" src="img/detailsquare.jpg" alt="..." width="70"></a></li>
                <li class="list-inline-item mb-2 me-2 pb-1"><a href="#"><img class="img-fluid" src="img/detailsquare2.jpg" alt="..." width="70"></a></li>
                <li class="list-inline-item mb-2 me-2 pb-1"><a href="#"><img class="img-fluid" src="img/detailsquare3.jpg" alt="..." width="70"></a></li>
                <li class="list-inline-item mb-2 me-2 pb-1"><a href="#"><img class="img-fluid" src="img/detailsquare3.jpg" alt="..." width="70"></a></li>
                <li class="list-inline-item mb-2 me-2 pb-1"><a href="#"><img class="img-fluid" src="img/detailsquare2.jpg" alt="..." width="70"></a></li>
                <li class="list-inline-item mb-2 me-2 pb-1"><a href="#"><img class="img-fluid" src="img/detailsquare.jpg" alt="..." width="70"></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!-- COPYRIGHTS-->
      <div class="bg-dark py-5">
        <div class="container">
          <div class="row align-items-cenrer gy-3 text-center">
            <div class="col-md-12 text-md-center">
              <p class="mb-0 text-sm text-gray-500">&copy; 2021.Husol Organization</p>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!--/.Footer-->
  </div>
  <div id="loading" class="notification_box">
    <p><span id="infoText">Processing...</span></p>
    <i class="fas fa-spinner fa-pulse text-dark mt-1 float-right"></i>
  </div>
  <?= $this->inlineScript()
    ->prependFile($this->basePath("js/common.{$this->layout()->dateVersion}.js"))
  ?>
</body>
</html>